import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;


public class Rnd1 {
	
	public static int counter = 0;
	
	
	
	private static void logToCSVFile(StringBuffer sb) {
	try {
	 
	String content = sb.toString();
 
	File file = new File("C:\\Java\\UniProt\\log_disorder.txt");
 
	if (!file.exists()) {
	file.createNewFile();
	}
 
	FileWriter fw = new FileWriter(file.getAbsoluteFile());
	BufferedWriter bw = new BufferedWriter(fw);
	bw.write(content);
	bw.close();
 
	System.out.println("Done");
 
	} catch (IOException e) {
	e.printStackTrace();
	}
	}
	
	public static int countOccurences(String sequence, String query) {
		Pattern pattern = Pattern.compile(query);
		Matcher  matcher = pattern.matcher(sequence);
		
		int count = 0;
        while (matcher.find()) {
            count++;
        }
        return count;
	}

	public static void aaSequenceToTypes(String aaSequence) {
		
		aaSequence = aaSequence.replaceAll("([A-Z]{1})", "-$1-");
		//aaSequence = aaSequence.replaceAll("--", "-");
		
		System.out.println();
		System.out.println();
		System.out.println();
		counter++;
		System.out.println("counter =========> " + counter);
		System.out.println("*************************");
		System.out.println(aaSequence);
		System.out.println("*************************");
		
		//NPR = Nonpolar, aliphatic R groups
		//Glycine, Alanine, Valine, Leucine, Methionine, Isoleucine
		aaSequence = aaSequence.replaceAll("(-)(G|A|V|L|M|I)(-)", "$1sssNPRsss$3");

 
		//PUR = Polar, uncharged R groups
		//Serine, Threonine, Cystine, Proline, Asparagine, Glutamine
		aaSequence = aaSequence.replaceAll("(-)(S|T|C|P|N|Q)(-)", "$1sssPURsss$3");

		
		//AR = Aromatic R groups
		//Phenylalanine, Tyrosine, Tryptophan
		aaSequence = aaSequence.replaceAll("(-)(F|Y|W)(-)", "$1sssARsss$3");
		

		//PR = Positively charged R groups
		//Lysine, Arginine, Histidine
		aaSequence = aaSequence.replaceAll("(-)(K|R|H)(-)", "$1sssPRsss$3");
 
		
		//NR = Negatively charged R groups
		//Aspartate, Glutamate
		aaSequence = aaSequence.replaceAll("(-)(D|E)(-)", "$1sssNRsss$3");
 
		aaSequence = aaSequence.replaceAll("--", "-");
 
		System.out.println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");
		System.out.println(aaSequence);
		int totalOccurences = countOccurences(aaSequence,"sss") / 2;
		
		int countNPR = countOccurences(aaSequence,"sssNPRsss");
		int countPUR = countOccurences(aaSequence,"sssPURsss");
		int countAR  = countOccurences(aaSequence,"sssARsss");
		int countPR  = countOccurences(aaSequence,"sssPRsss");
		int countNR  = countOccurences(aaSequence,"sssNRsss");
		
		float percentageNPR = (float)countNPR/totalOccurences;
		float percentagePUR = (float)countPUR/totalOccurences;
		float percentageAR  = (float)countAR/totalOccurences;
		float percentagePR  = (float)countPR/totalOccurences;
		float percentageNR  = (float)countNR/totalOccurences;
		
		
		System.out.println("number of residues = "+totalOccurences);
		System.out.println("NPR = Nonpolar, aliphatic R groups = "+countNPR+"/"+totalOccurences+" percentage = "+percentageNPR);
		System.out.println("PUR = Polar, uncharged R groups = "+countPUR+"/"+totalOccurences+" percentage = "+percentagePUR);
		System.out.println("AR = Aromatic R groups  = "+countAR+"/"+totalOccurences+" percentage = "+percentageAR);
		System.out.println("PR = Positively charged R groups  = "+countPR+"/"+totalOccurences+" percentage = "+percentagePR);
		System.out.println("NR = Negatively charged R groups  = "+countNR+"/"+totalOccurences+" percentage = "+percentageNR);
		
		System.out.println("percentage NPR+PUR ====>"+((float)(percentageNPR+percentagePUR)));
		
		System.out.println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");		
		if(0.5 < (percentageNPR+percentagePUR) ) {
			System.out.println("=========>Rule OK");
		} else {
			System.out.println("=========>Rule NO");
		}
		
		System.out.println();
		System.out.println();
		System.out.println();
		
		//return aaSequence;
		
	}
	
	
	public static void main(String[] args) {
		String seq01 = "MSTEASVSYAALILADAEQEITSEKLLAITKAAGANVDQVWADVFAKAVEGKNLKELLFSFAAAAPASGAAAGSASGAAAGGEAAAEEAAEEEAAEESDDDMGFGLFD";
		String seq02 = "GDVEKGKKIFVQKCAQCHTVEKGGKHKTGPNLHGLFGRKTGQAPGFTYTDANKNKGITWKEETLMEYLENPKKYIPGTKMIFAGIKKKTEREDLIAYLKKATNE";
		String seq03 = "EQEFSDNELQELSTQGSRYV";
		String seq04 = "KAQNREP";
		String seq05 = "RIHKIGEVHEGAATMDFMEQERERGITITAA";
		String seq06 = "GDVPAKAEAGAEAGGGAGPGAEDEAGRSAVGDPELGDPPAAPQ";
		String seq07 = "DLSKAVSLSMGLYMGETETKVMGNDLGFPQQGQISLSSGETDLKLLEESIANLNRSTSVPENPKSSASTAVSAAPTEKEFPKTHSDVSSEQQHLKGQTGTNGGNVKLYTTDQSTFDILQDLEFSSGSPGKETNESPWRSDLLIDENCLLSPLAGEDDSFLLEGNSNEDCKPLILPDTKPKIKDNGD";
		String seq08 = "MGHNDSVETMDEISNPNNILLPHDGTGLDATGISGSQEPYGMVDVLNPDSLKDDSNVDEPLIEDIVNPSLDPEGVVSAEPSNEVGTPLLQQPISLDHVITRPASAGGVYSIGNSSTSSAAKLSDGDLTNATDPLLNNAHGHGQPSSESQSHSNGYHKQGQSQQPLLSLNKRKLLAKAHVDKHHSKKKLSTTRARP";
		String seq09 = "MSESSSKSSQPLASKQEKDGTEKRGRGRPRKQPPVSPGTALVGSQKEPSEVPTPKRPRGRPKGSKNKGAAKTRKTTTTPGRKPRGRPKKLEKEEEEGISQESSEEEQ";
		String seq10 = "PKRKSATKGDEPARRSARLSARPVPKPAAKPKKAAAPKKAVKGKKAAENGDAKAEAKVQAAGDGAGNAK";
		String seq11 = "GFGPSPFSLTEGLPKIPSISTHIKVKSEEMIKVVEKSEKETVIVEGQTEEIRVTEGVTEEEDKEAQGQEGEEAEEGEEKEEEELAAATSPPAEEAASPEKETKSRVKEEAKSPGEAKSPGEAKSPAEAKSPGEAKSPGEAKSPGEAKSPAEPKSPAEPKSPAEAKSPAEPKSPATVKSPGEAKSPSEAKSPAEAKSPAEAKSPAEAKSPAEAKSPAEAKSPAEAKSPATVKSPGEAKSPSEAKSPAEAKSPAEAKSPAEAKSPAEVKSPGEAKSPAEPKSPAEAKSPAEVKSPAEAKSPAEVKSPGEAKSPAAVKSPAEAKSPAAVKSPGEAKSPGEAKSPAEAKSPAEAKSPIEVKSPEKAKTPVKEGAKSPAEAKSPEKAKSPVKEDIKPPAEAKSPEKAKSPVKEGAKPPEKAKPLDVKSPEAQTPVQEEATVPTDIRPPEQVKSPAKEKAKSPEKEEAKTSEKVAPKKEEVKSPVKEEVKAKEPPKKVEEEKTLPTPKTEAKESKKDEAPKEAPKPKVEEKKETPTEKPKDSTAEAKKEEAGEKKKAVASEEETPAKLGVKEEAKPKEKTETTKTEAEDTKAKEPSKPTETEKPKKEEMPAAPEKKDTKEEKTTESRKPEEKPKMEAKVKEDDKSLSKEPSKPKTEKAEKSSSTDQKESQPPEKTTEDKATKGEK";
		String seq12 = "APQQTEVAEEIVEEETVVEETGVPVGANPVQVEMGEFEDGAEETVEEVVADNPCQNHHCKHGKVCELDESNTPMCVCQDPTSCPAPIGEFEKVCSNDNKTFDSSCHFFATKCTLEGTKKGHKLHLDYIGPCKYIAPCLDSELTEFPLRMRDWLKNVLVTLYERDEGNNLLTEKQKLRVKKIHENEKRLEAGDHPVELLARDFEKNYNMYIFPVHWQFGQLDQHPIDGYLSHTELAPLRAPLIPMEHCTTRFFETCDLDNDKYIALEEWAGCFGIKEQDINKDLVI";
		String seq13 = "MDQRQKLQHWIHSCLRKADKNKDNKMNFKELKDFLKELNIQVDDGYARKIFRECDHSQTDSLEDEEIETFYK";
		String seq14 = "CENDGVGGNLLCSYGTPPDSPGNLLSFPRFFGPGE";
		String seq15 = "MSSNCTSTTAVAVAPLSASKTKTKKKHFVCQKV";
		String seq16 = "MARYRRSRTRSRSPRSRRRRRRSGRRRSPRRRRRYGSARRSRRSVGGRRRRYGSRRRRRRRY";
		String seq17 = "MSDAAVDTSSEITTKDLKEKKEVVEEAENGRDAPANGNAQNEENGEQEADNEVDEEEEEGGEEEEEEEEGDGEEEDGDEDEEAEAPTGKRVAEDDEDDDVETKKQKKTDEDD";
		String seq18 = "PYSDRMKKLIEDPDKFYTPKTRPSGHDIGKSFSKDNGG";
		String seq19 = "PVPYNEGLGQPQVAPPAPAASPAASSRPQPQNGSSGMGSTVSKAYGASKTFGKA";
		String seq20 = "MCKGLAGLPASCLRSAKDMKHRLGFLLQKSDSCEHSSSHSKKDKVVTCQR";
		String seq21 = "MPVAGSELPRRPLPPAAQERDAEPRPP";
		String seq22 = "KGSTNAKELSSKGVKIWDANGSRDFLDSLGFSTREEGDLG";
		String seq23 = "FGAEYRDMESDYSGQG";
		String seq24 = "MTMTLHTKASGMALLHQIQGNELEPLNRPQLKIPLERPLGEVYLDSSKPAVYNYPEGAAYEFNAAAAANAQVYGQTGLPYGPGSEAAAFGSNGLGGFPPLNSVSPSPLMLLHPPPQLSPFLQPHGQQVPYYLENEPSGYTVREAGPPAFYRPNSDNRRQGGRERLASTNDKGSMAMESAKETRY";
		String seq25 = "CPATNQCTIDKNRRKSC";
		String seq26 = "GGIRKDRRGG";
		String seq27 = "DKDYIDLAFSKKKADDRKEWLRQYEPGTVLDPTLKEIPISDFINKELI";
		String seq28 = "EQINDVKGATSDEEDEESSHEDTENVINGPE";
		String seq29 = "GNVPNKGSKTKGKGKRKLVDDEDY";
		String seq30 = "MSGDHLHNDSQIEADFRLNDSHKHKDKHKDREHRHKEHKKEKDREKSKHSNSEHKDSEKKHKEKEKTKHKDGSSEKHKDKHKDRDKEKRKEEKVRASGDAKIKKEKENGFSSPPQIKDEPEDDGYFVPPKEDIKPLKRPRDEDDADYKPKKIKTEDTKKEKKRKLEEEEDGKLK";
		String seq31 = "MSGDHLHNDSQIEADFRLNDSHKHKDKHKDREHRHKEHKKEKDREKSKHSNSEHKDSEKKHKEKEKTKHKDGSSEKHKDKHKDRDKEKRKEEKVRASGDAKIKKEKENGFSSPPQIKDEPEDDGYFVPPKEDIKPLKRPRDEDDADYKPKKIKTEDTKKEKKRKLEEEEDGKLKKPKNKDKDKKVPEPDNKKKKPKK";
		String seq32 = "MSVASLDLTGGLPEVATPESEEAFTLPLLNDPEPKPSVEPVKSISSMELKTEPFDDFLFPASSRPSGSETARSVPDMDLSGSFYAADWEPLHSGSLGMGPMATELEPLCTPVVTCTPSCTAYTSSFVFTYPEADSFPSCAAAHRKGSSSNEPSSDSLSSPTLLAL";
		String seq33 = "MAHKKAGGSTRNGRDSEAKRLGVKRFGGESVLAGSIIVRQRGTKFHAGANVGCGRDHTLFAKADGKVKFEVKGPKNRKFISIEAE";
		String seq34 = "MAKGIREKIKLVSSAGTGHFYTTTKNKRTKPEKLELKKFDPVVRQHVIYKEAKIK";
		String seq35 = "TKAGQGTSAPPEASPTAAPESSTSFPPAPTSGMSHPPPAAREDKSPSEESAPTTSPESVSGSVPSSGSSGREEDAASTLVTG";
		String seq36 = "IQRQLEITGRTTTSEELEDMLESGNPAIFASGII";
		String seq37 = "MSTQQQARALMMRHHQFIKNRQQSMLSRAAAEIGVEAEKDFWTTVQGKPQSSFRTTYDRSNASLS";
		String seq38 = "GEATTIWGVGADEAIDKGTPSKNDLQNMSADLAKNGFKGHQGVACSTVKDGNKDVYMIKFSLAGGSNDPGGSPCSDD";
		String seq39 = "SKSSKEQKKKQK";
		String seq40 = "MKVLILACLVALALARETIESLSSSEESITEYKQKVEKVKHEDQQQGEDEHQDKIYPSFQPQPLIYPFVEPIPYGFLPQNILPLAQPAVVLPVPQPEIMEVPKAKDTVYTKGRVMPVLKSPTIPFFDPQIPKLTDLENLHLPLPLLQPLMQQVPQPIPQTLALPPQPLWSVPQPKVLPIPQQVVPYPQRAVPVQALLLNQELLLNPTHQIYPVTQPLAPVHNPISV";
		String seq41 = "MMKSFFLVVTILALTLPFLGAQEQNQEQPIRCEKDERFFSDKIAKYIPIQYVLSRYPSYGLNYYQQKPVALINNQFLPYPYYAKPAAVRSPAQILQWQVLSNTVPAKSCQAQPTTMARHPHPHLSFMAIPPKKNQDKTEIPTINTIASGEPTSTPTTEAVESTVATLEDSPEVIESPPEINT";
		String seq42 = "AVPVESKPDKPSGKSGMDAALDDLIDTLGGPEETEEENTTYTGPEVSDPMSSTYIEELGKREVTIPPKYRELLAKKEGITGPPADSSKPIGPDDAIDALSSDFTCGSPTAAGKKTEKEESTEVLKAQSAGTVRSAAPPQEK";
		String seq43 = "MQHWLDKLTDLAAIEGDECILKTGLADIADHFGFTGYAYLHIQHRHITAVTNYHRQWQSTYFDKKFEALDPVVKRARSRKHIFTWSGEHERPTLSKDERAFYDHASDFGIRSGITIPIKTANGFMSMFTMASDKPVIDLDREIDAVAAAATIGQIHARISFLRTTPTAEDAAWLDPKEATYLRWIAVGKTMEEIADVEGVKYNSVRVKLREAMKRFDVRSKAHLTALAIRRKLI";
		String seq44 = "MAKRVADAQIQRETYDSNESDDDVTPSTKVASSAVMNRRKIAMPKRRMAFKPFGSAKSDETKQASSFSFLNRADGTGEAQVDNSPTTESNSRLKALNLQFKAKVDDLVLGKPLADLRPLFTRYELYIKNILEAPVKSIENPTQTKGNDAKPAKVEDVQKSSDSSSEDEVKVEGPKFTIDAKPPISDSVFSFGPKKENRKKDESDSENDIEIKGPEFKFSGTVSSDVFKLNPSTDKNEKKTETNAKPFSFSSATSTTEQTKSKNPLSLTEATKTNVDNNSKAEASFTFGTKHAADSQNNKPSFVFGQAAAKPSLEKSSFTFGSTTIEKKNDENSTSNSKPEKSSDSNDSNPSFSFSIPSKNTPDASKPSFSFGVPNSSKNETSKPVFSFGAATPSAKEASQEDDNNNVEKPSSKPAFNLISNAGTEKEKESKKDSKPAFSFGISNGSESKDSDKPSLPSAVDGENDKKEATKPAFSFGINTNTTKTADTKAPTFTFGSSALADNKEDVKKPFSFGTSQPNNTPSFSFGKTTANLPANSSTSPAPSIPSTGFKFSLPFEQKGSQTTTNDSKEESTTEATGNESQDATKVDATPEESKPINLQNGEEDEVALFSQKAKLMTFNAETKSYDSRGVGEMKLLKKKDDPSKVRLLCRSDGMGNVLLNATVVDSFKYEPLAPGNDNLIKAPTVAADGKLVTYIVKFKQKEEGRSFTKAIEDAKKEMK";
		String seq45 = "LNKWKSKGRRFKGKGKGNKAAQPGSGKGKVQFQGKKTKFASDDEHDEHDENGATGPVKRAREETDKEEPASKQQKTENGAGDQ";
		String seq46 = "CSPLRHSFQKQQREKTRWLNSGRGDEASEEGQNGSSPKSKTKWTKEDGHRTSTSAVPNLFVPLNTNPKEVQEMRNKIREQNLQDIKTAGPQSQVLCGVVMDRSLVQGELVTASKAIIEKEYQPHVIVSTTGPNPFTTLTDRELEEYRREVERKQKGSEENLDEAREQKEKSPPDQPAVPHPPPSTPIKLEEDLVPEPTTGDDSDAATFKPTLPDLSPDEPSEALGFPMLEKEEEAHRPPSPTEAPTEASPEPAPDPAPVAEEAAPSAVEEGAAADPGSDGSPGKSPSKKKKKFRTPSFLKKSKKKSDS";
		String seq47 = "EFKLELVEKLFAEDTEAKNPFSTQDTDLDLEMLAPYIPMDDDFQLRSFDQLSPLESSSASPESASPQSTVTVFQQTQIQEPTANATTTTATTDELKTVTKDRMEDIKILIASPSPTHIHKETTSATSSPYRDTQSRTASPNRAGKGVIEQTEKSHPRSPNVLSVALSQR";
		String seq48 = "AAGDTIISLDFGSNDTETDDQQLEEVPLYNDVMLPSPNEKLQNINLAMSPLPTAETPKPLRSSADPALNQEVALKLEPNPESLELSFTMPQIQDQTPSPSDGSTRQSSPEPNSPSEYCFYVDSDMVNEFKLELVEKLFAEDTEAKNPFSTQDTDLDLEMLAPYIPMDDDFQLRSFDQLSPLESSSASPESASPQSTVTVFQ";
		String seq49 = "SDLACRLLGQSMDESGLPQLTSYDCEVNAPIQGSRNLLQGEELLRALDQVN";
		String seq50 = "ALNEGQIVTLAVDEIIETISAITPMAQKAKKYTPPAASMQRSSNTIWMPVEQESPTQEGWDLTDKATGLLELNVAVNMGEPDNDFFQLRADDLRDETAYRRRIQSAARKLANNVELKVANMAAEMGSLVITSPDAIGTNTADAWNFVADAEEIMFSRELNRDMGTSYFFNPQDYKKAGYDLTKRDIFGRI";
		String seq51 = "SERTGTQPLGVQ";
		String seq52 = "MIPQHHDQDQLIATIATAPQQTVHAQVVEDIHHQGQILQATTQTNAAGQQQTIVTTDAAKHDQAVIQAFLPARKRKPRVKKMSPTAPKISKVEGMDTIMGTPTSSHGSGSVQQVLGENGAEGQLLSSTPIIKSEGQKVETILTMDPNNMIPVTSANAATGEITPAQGATGSSGGNTSGVLSTPKAKRAKHPPGTEKPRSRSQSEQPATCPICYAVIRQSRNLRRHLELRHFAKPGVKKEKKSKSGNDTTLDSSMEMNTTAEGDNTVGSDGAGGAGSAGGQSSGTTPTRVISNAPQAAGAPAILAQGVLPQQQQQQQLQQQHQQHLTATLAGGGQAYIKHEGGGGGGTGQQQQQQAAQQQGMQNVIHIVGDQVFIPQQQQPQPQ";
		String seq53 = "GNTSGVLSTPKAKRAKHPPGTEKPRS";
		String seq54 = "SERTAQAQARLQTEKQLLSWVSENANDIVTLRAQGGSDAPSD";
		String seq55 = "KKRPKPGGWNTGGSRYPGQGSPGGNRYPPQGGGGWGQPHGGGWGQPHGGGWGQPHGGGWGQPHGGGWGQGGGTHSQWNKPSKPKTNMKHMAGAAAAGAV";
		String seq56 = "GTQNRPLLRNSLDDLVGPPSNLEGQSDERALLDQLHTLLSNTDATGLEEIDRALGIPELVNQGQALEPKQD";
		String seq57 = "MSGGDGRGHNTGAHSTSGNINGGPTGIGVSGGASDGSGWSSENNPWGGGSGSGIHWGGGSGRGNGGGNGNSGGGSGTGGNLSA";
		String seq58 = "PNRSISPSALQDLLRTLKSPSSPQQQQQVLNILKSNPQLMAAFIKQRTAKYVANQPGMQ";
		String seq59 = "MPREFKSFGSTEKSLLSKGHGEPSYSEI";
		String seq60 = "QPGMQPQPGLQSQPGMQPQPGMHQQPSLQNLNAMQAGVPR";
		String seq61 = "EGFNQSSHQKNVDAR";
		String seq62 = "MKAKRSHQAIIMSTSLRVSPSIHGYHFDTASRKKAVGNIFENTDQESLERLFRNSGDKKAEERAKIIFAIDQDVEEKTRALMALKKRTKDKLFQFLKLRKYSIKVH";
		String seq63 = "ISSYYLSHKRIIPSSML";
		String seq64 = "NLGIDFEDIRHMQNEKFFRNDFSGEVDFRDIDLTDEILTYVQDSLSKSPFIPSDYQQQQSLALNSSCMVQEHLHLEQQQQHHQKQVVVEPQQQLCQKMKHMQVNGMFENWNSNQFVPFNCPQQDPQQYNVFTDLHGISQEFPYKSEMDSMPYTQNFISCNQPVLPQHSK";
		String seq65 = "TGSTEIGRVIQVAAGSSNLKRVTLELGGK";
		String seq66 = "SPFGGYKMSGSGRELG";
		String seq67 = "EEEDDEEDEEDEEEEEEEEDEDEEEDDDDE";
		String seq68 = "KTKVAKVSQGVEDGPDTKRAKLDSSE";
		String seq69 = "LDKDDSKAGMEEDHTYEGLDIDQTATYEDIVTLRTGEVKWSVGEHPGQE";
		String seq70 = "GGGVSPDVCPALSDEPGGLTASRGRVHEASPPTFQKDALLGSKPNKPSLPSSSQNLGQTEVSKVSETVQEELTPPPQKAAPQGKSKSDPLKKKTDR";
		String seq71 = "DHTDGAKVKGGAKGKGKAAAKAAKGKKLSAKKGDSSAADVRKSVDKIVKYTPSKGSRKDTPQKSQAPAAGKSSAKKGGKKAVPSAPSPSGKKSALTTDKMTMAQFVKYLDWHEKKKGGKVSSGGKVLGKRSAGKASATSGKASKASKKTAAKK";
		String seq72 = "MPQSSRAQTL";
		String seq73 = "PVISTQTSPVPAPRTRKNKQTQASYPVSIKTSVERGQRAKRKVQRDARPRNYKIAGIHDGLQTLAQAALPAHGWGRQDPRHKSRNLGILLDYPLGWIGDVTTHTPLVGPLVAGAVVRPVCQIVRLLEDGVNWATGWFGVHLFVVCLLSLACPCSG";
		String seq74 = "PVISTQTSPVPAPRTRKNKQTQASYPVSIKTSVERGQRAKRKVQRDARPRNYKIAGIHDGLQTLAQAALPAHGWGRQDPRHKSRNLGILLDYPLGWIGDVTTHTPLVGPLVAGAVVRPVCQIVRLLEDGVNWATGWFGVHLFVVCLLSLACPCSG";
		String seq75 = "SLSNLHSLDRSTREVELGLEYGSPTMNLAGQ";
		String seq76 = "GVSGGVDRREVQRLRRRNQQLEEENNLLRLKVDILLDMLSESTAESHLMEKELDELRISRKRK";
		String seq77 = "MPFFGNTFSPKKTPPRKSA";
		String seq78 = "SLSNLHSLDRSTREVELGLEYGSPTMNLAGQ";
		String seq79 = "SLKFENGQWIAET";
		String seq80 = "GVSGGVDRREVQRLRRRNQQLEEENNLLRLKVDILLDMLSESTAESHLMEKELDELRISRKRK";
		String seq81 = "TTPPSVYPLAPGSAAQTNSMVTLGCLVKGYFPEPVTVTWNSGSLSSGVHTFPAVLQSDLYTLSSSVTVPSSTWPSETVTCNVAHPASSTKVDKKIVPR";
		String seq82 = "MTYMCSILICLVLILCARGAEA";
		String seq83 = "MTWMKMFYLTLAVTAAVLLVTVAA";
		String seq84 = "ADDDEDASSGLCNQYNQNVTTRPNNKPKMF";
		String seq85 = "MTYMCSILICLVLILCARGAEA";
		String seq86 = "ANPNTLGDGSQAENQKPI";
		String seq87 = "MAEVVNISKSASFSKQEKEFSDFQKSKESNEKILNKESNRFTLHPI";
		String seq88 = "MDLISLQGKTNFFEKRVADYQKSGVMAQRKEQVFSLNTDF";
		String seq89 = "RSSWYWGRLSRQEAVALLQGQRHGVFLVRDSSTSPGDYVLSVSENSRVSHYIINSSGPRPPVPPSPAQPPPGVSPSRLRIGDQEFDSLPALLEFYKIHYLDTTTLIEPVSR";
		String seq90 = "AEYVRALFDFNGNDEEDLPFKKGDILRIRDKPEEQWWNAEDSEGKRGMIPVPYVEKYR";
		String seq91 = "MRGRLQGVALIARDWI";
		String seq92 = "INFRPEDRIKRGLMMLKRAKGVWI";
		String seq93 = "MSGRPRTTSFAESCKPVQQPSAFGSMKVSRDKDG";
		String seq94 = "AASTPTNATAASDANTGDRGQTNNAASASASNST";
		String seq95 = "NPNYTEFKFPQIKAH";
		String seq96 = "CGGSWREDWGQLSGTAVPPQGAEPQSNAGPRPHIGDT";
		String seq97 = "MVDLKRLRQEPEVFHRAIREKGVALDLEALLALDREVQELKKRLQEVQTERNQVAKRVPKAPPEEKEALIARGKALGEEAKRLEEALREKEARLEALLLQVPLPPWPGAPV";
		String seq98 = "TVVRRVRALYDLTTNEPDELSFRKGDVITVLEQVYRDWWKGALRGNMGIFPLNYVTPIVE";
		String seq99 = "EVQELKKRLQEVQTERNQVAKRVPKAPPEEKEALIARGKALGEEAKRLEEALRE";
 
		
		
		
		
		aaSequenceToTypes(seq01);
		aaSequenceToTypes(seq02);
		aaSequenceToTypes(seq03);
		aaSequenceToTypes(seq04);
		aaSequenceToTypes(seq05);
		aaSequenceToTypes(seq06);
		aaSequenceToTypes(seq07);
		aaSequenceToTypes(seq08);
		aaSequenceToTypes(seq09);
		aaSequenceToTypes(seq10);
		aaSequenceToTypes(seq11);
		aaSequenceToTypes(seq12);
		aaSequenceToTypes(seq13);
		aaSequenceToTypes(seq14);
		aaSequenceToTypes(seq15);
		aaSequenceToTypes(seq16);
		aaSequenceToTypes(seq17);
		aaSequenceToTypes(seq18);
		aaSequenceToTypes(seq19);
		aaSequenceToTypes(seq20);
		aaSequenceToTypes(seq21);
		aaSequenceToTypes(seq22);
		aaSequenceToTypes(seq23);
		aaSequenceToTypes(seq24);
		aaSequenceToTypes(seq25);
		aaSequenceToTypes(seq26);
		aaSequenceToTypes(seq27);
		aaSequenceToTypes(seq28);
		aaSequenceToTypes(seq29);
		aaSequenceToTypes(seq30);
		aaSequenceToTypes(seq31);
		aaSequenceToTypes(seq32);
		aaSequenceToTypes(seq33);
		aaSequenceToTypes(seq34);
		aaSequenceToTypes(seq35);
		aaSequenceToTypes(seq36);
		aaSequenceToTypes(seq37);
		aaSequenceToTypes(seq38);
		aaSequenceToTypes(seq39);
		aaSequenceToTypes(seq40);
		aaSequenceToTypes(seq41);
		aaSequenceToTypes(seq42);
		aaSequenceToTypes(seq43);
		aaSequenceToTypes(seq44);
		aaSequenceToTypes(seq45);
		aaSequenceToTypes(seq46);
		aaSequenceToTypes(seq47);
		aaSequenceToTypes(seq48);
		aaSequenceToTypes(seq49);
		aaSequenceToTypes(seq50);
		aaSequenceToTypes(seq51);
		aaSequenceToTypes(seq52);
		aaSequenceToTypes(seq53);
		aaSequenceToTypes(seq54);
		aaSequenceToTypes(seq55);
		aaSequenceToTypes(seq56);
		aaSequenceToTypes(seq57);
		aaSequenceToTypes(seq58);
		aaSequenceToTypes(seq59);
		aaSequenceToTypes(seq60);
		aaSequenceToTypes(seq61);
		aaSequenceToTypes(seq62);
		aaSequenceToTypes(seq63);
		aaSequenceToTypes(seq64);
		aaSequenceToTypes(seq65);
		aaSequenceToTypes(seq66);
		aaSequenceToTypes(seq67);
		aaSequenceToTypes(seq68);
		aaSequenceToTypes(seq69);
		aaSequenceToTypes(seq70);
		aaSequenceToTypes(seq71);
		aaSequenceToTypes(seq72);
		aaSequenceToTypes(seq73);
		aaSequenceToTypes(seq74);
		aaSequenceToTypes(seq75);
		aaSequenceToTypes(seq76);
		aaSequenceToTypes(seq77);
		aaSequenceToTypes(seq78);
		aaSequenceToTypes(seq79);
		aaSequenceToTypes(seq80);
		aaSequenceToTypes(seq81);
		aaSequenceToTypes(seq82);
		aaSequenceToTypes(seq83);
		aaSequenceToTypes(seq84);
		aaSequenceToTypes(seq85);
		aaSequenceToTypes(seq86);
		aaSequenceToTypes(seq87);
		aaSequenceToTypes(seq88);
		aaSequenceToTypes(seq89);
		aaSequenceToTypes(seq90);
		aaSequenceToTypes(seq91);
		aaSequenceToTypes(seq92);
		aaSequenceToTypes(seq93);
		aaSequenceToTypes(seq94);
		aaSequenceToTypes(seq95);
		aaSequenceToTypes(seq96);
		aaSequenceToTypes(seq97);
		aaSequenceToTypes(seq98);
		aaSequenceToTypes(seq99);
 
		
		
		
		
		
		
		
		
		
		
		/*
		String seq08 = "ssssssssss";
		String seq09 = "ssssssssss";
		String seq10 = "ssssssssss";
		String seq11 = "ssssssssss";
		String seq12 = "ssssssssss";
		String seq13 = "ssssssssss";
		String seq14 = "ssssssssss";
		String seq15 = "ssssssssss";
		String seq16 = "ssssssssss";
		String seq17 = "ssssssssss";
		String seq18 = "ssssssssss";
		String seq19 = "ssssssssss";
		String seq20 = "ssssssssss";
		String seq21 = "ssssssssss";
		String seq22 = "ssssssssss";
		String seq23 = "ssssssssss";
		String seq24 = "ssssssssss";
		String seq25 = "ssssssssss";
		String seq26 = "ssssssssss";
		*/

	}

}
